/**
 * Created by mac_ori on 09/11/2017.
 */
public enum Action {
    LEFT_ROTATE,
    RIGHT_ROTATE,
    FLIP,
    UP_TWIST_LEFT,
    UP_TWIST_RIGHT,
    DOWN_TWIST_RIGHT,
    DOWN_TWIST_LEFT,
    LEFT_TWIST_FRONTUPWARD,
    LEFT_TWIST_BACKUPWARD,
    RIGHT_TWIST_FRONTUPWARD,
    RIGHT_TWIST_BACKUPWARD,
    FRONT_TWIST_CLOCKWISE,
    FRONT_TWIST_C_CLOCKWISE,
    BACK_TWIST_CLOCKWISE,
    BACK_TWIST_C_CLOCKWISE
}
